### ISSUE TITLE
[SIEP] - Add End-of-Life field to Security Insights specification

### ISSUE THREAD

**Issue by jorfde** [ossf/security-insights-spec#122]
### Proposal Summary

Add an "end_of_life" field to the Security Insights specification to allow projects to communicate their EOL status and policy

### Detailed Design

Security Insights lacks a way to indicate when software has reached or is approaching EOL status. This is critical security information that can't be reliably determined through automated scanning.

This issue proposes to add an ```end_of_life``` field at the root level of the specification:

#### Root level field:
```
end_of_life:
  status: false  # true if EOL
  planned_date: "2026-12-31"  # ISO date, optional
  notice_url: "https://example.com/eol-announcement"  # optional
  policy_url: "https://example.com/lifecycle-policy"  # optional
```

### Positive:

* Provides critical security information that users need when evaluating software
* Aligns with user story to "know project status, release cycle time, security maintenance, and project end of life"
* Allows consumers to make informed security decisions and plan for migrations

### Negative:

* None significant; this is a straightforward addition

### Compatibility

This proposal maintains backward compatibility as it only adds a new optional field. Existing Security Insights files will continue to validate correctly without this field.

### Alternatives

The field could also be placed within the project section:

```
project:
  # existing fields...
  end_of_life:
    status: false
    planned_date: "2026-12-31"
    notice_url: "https://example.com/eol-announcement"
    policy_url: "https://example.com/lifecycle-policy"
```

### Open Questions

Should we add an additional field for indicating whether security patches will still be provided after EOL?

### Sponsoring Maintainer Assigned

{"label" => "No Sponsor Yet", "value" => "None"}
