### ISSUE TITLE
Change value "sbom-name" to "sbom-format"

### ISSUE THREAD

**Issue by eddie-knight** [ossf/security-insights-spec#25]
This is part of #26

Looking at the yaml examples, the meaning of `sbom-name` was not immediately clear. My suggestion is to adjust this to be `sbom-format` instead, to increase clarity.

Current Schema:

```
sbom:
    $id: '#/properties/dependencies/properties/sbom'
    additionalItems: false
    items:
        anyOf:
        -   $id: '#/properties/dependencies/properties/sbom/items'
            additionalProperties: false
            properties:
                sbom-file:
                    $id: '#/properties/dependencies/items/anyOf/0/properties/sbom-file'
                    description: 'Link to the SBOM file.'
                    type: string
                    format: iri
                    pattern: '^https?:\/\/'
                sbom-name:
                    $id: '#/properties/dependencies/items/anyOf/0/properties/sbom-name'
                    description: 'Name of the SBOM standard used.'
                    type: string
                sbom-url:
                    $id: '#/properties/dependencies/items/anyOf/0/properties/sbom-url'
                    description: 'Link to the SBOM standard website or documentation.'
                    type: string
                    format: iri
                    pattern: '^https?:\/\/'
```
