### ISSUE TITLE
Extend the SBOM schema

### ISSUE THREAD

**Issue by eddie-knight** [ossf/security-insights-spec#27]
This issue is part of #26.

Currently, the SBOM example is:

```yaml
  sbom:
  - sbom-file: https://foo.bar/sbom
    sbom-name: CycloneDX
    sbom-url: https://foo.bar
```

In addition to the suggestion contained within #25, it may be prudent to add the following values to the SBOM schema:

- `sbom-creation: | Lorum Ipsum...` 
    - Description of how the SBOM is created (it is expected that the SBOM is automatically generated upon every release, but the 2022 Cloud Native Security Slam showed us that projects often cut corners by manually generating their SBOMs)
- `sbom-generated: DATETIME`
    - Allowing end users to automatically compare the release date to the SBOM generation date can increase trust in the information. This suggestion is debatable, especially considering that the previous value solves a similar need.
