### ISSUE TITLE
Add release and provenance values to schema

### ISSUE THREAD

**Issue by eddie-knight** [ossf/security-insights-spec#29]
This is part of #26 

Considering that provenance is one of the biggest issues that the OpenSSF seeks to address through its tooling and recommendations, it makes sense to encourage the documentation of related information.

Additionally, it is beneficial to both security researchers and end users when a project supplies information about its release cycle and automated release process.

The release value may look something like this:

```yaml
release:
  release-process: | Lorum ipsum...
  release-cycle: https://ubuntu.com/about/release-cycle
  provenance: https://....
```

It may be that we recommend external links for these values, or nesting descriptions within the document.
